### PR TITLE
Exp - 8 code review

### LINKED ISSUE #8: BUG - Wrong Aim, Objective and THeory
The aim, objective and theory sections have information belongigng to the CMOS inverter(https://github.com/virtual-labs/exp-transistor-level-inverter-iiith) and not of d flip flop in verilog.

image
image
image

### LINKED ISSUE #9: BUGS - Formatting Errors
1. *Browser Environment Info*: 
Google Chrome 113 on Linux(Ubuntu), Version 113.0.5672.92 (Official Build) (64-bit), X11 Window System. 
[Browser Details](https://whatismybrowser.com/w/QQYX8DK)
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36

---

**Type(s) of Issue**
- Formatting Issues

---

## Pretest Section

**Bug Screenshot**

image

**Description**
- Replace **SR** by **JK**.
---
## Practice Section

**Bug Screenshot**
image

**Description**
- Instruction invalid here
---
## Posttest Section

**Bug Screenshot**
image
image
image

**Description**
- correct option is option b
- correct answer is option b
- correct answer is option d

### LINKED ISSUE #10: Add contributors section

### LINKED ISSUE #11: BUG - Absence of simulate feature
1. *Browser Environment Info*: 
Google Chrome 113 on Linux(Ubuntu), Version 113.0.5672.92 (Official Build) (64-bit), X11 Window System. 
[Browser Details](https://whatismybrowser.com/w/QQYX8DK)
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
2. *Testing URL*: http://virtual-labs.github.io/exp-adder-circuit-iiith

**Type(s) of Issue**
- Technical Issue

**Bug Screenshot**
image

**Description**
THere is no feature to simulate and check circuit before validating. It is present along with the valodate option only. So, mention the given instruction instead of "Select the appropriate tab and click on validate after completion of circuit"

> Once you have built the required circuit and selected the input bit values, click on validate. This will give the output value as per the input bit set and will also give a success/failure message along with a graph with various input and output values for the correct circuit built.

### LINKED ISSUE #12: BUG - Pretest and Posttest - Red highlight upon wrong answer
1. *Browser Environment Info*: 
Google Chrome 113 on Linux(Ubuntu), Version 113.0.5672.92 (Official Build) (64-bit), X11 Window System. 
[Browser Details](https://whatismybrowser.com/w/QQYX8DK)
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36

---

**Type(s) of Issue**
- Technical Issue

**Bug Screenshot**
image

**Description**
It shows all options as red if we even select one wrong option even though correct option is one among them.

### PR DESCRIPTION
**Pull request by srisatyavinay**
Fixes #11 
Fixes #10 
Fixes #9 
Fixes #8 
Fixes #12

### CODE REVIEW

File: experiment/simulation/js/flipflop.js [hunk 1]
```diff
@@ -0,0 +1,89 @@
...
+
+	return permute(inputArr);
+}
+
+function flipflopValidate() {
+	const x = permutator([0, 1])
+	// console.log(x)
+	document.getElementById('error-container').style = 'display:none;';
+	circuitValid = 0
+	for (let i = 0; i < x.length; i++) {
```
Comment (vjspranav) [inline experiment/simulation/js/flipflop.js:29]: As thee is no assignment happening here
you could've probably used a forEach ? until unless it caused some problems.

File: experiment/simulation/js/flipflop.js [hunk 2]
```diff
@@ -0,0 +1,89 @@
...
+		}
+		if (connectionMap.has("input0$latch" + x[i][0]) && connectionMap.has("clockbar0$latch" + x[i][0]) && connectionMap.has("latch" + x[i][0] + "$latch" + x[i][1]) && connectionMap.has("latch" + x[i][1] + "$output0") && connectionMap.has("clock0$latch" + x[i][1]) && (connectionMap.size === 5) && selectedTab === currentTab.POS) {
+			circuitValid = 1
+			break
+		}
+	}
+	if (circuitValid) {
+		
+		let m = document.getElementById("input-selector").value;
+		if (selectedTab === currentTab.NEG && m === 1) {
```
Comment (vjspranav) [inline experiment/simulation/js/flipflop.js:42]: Maybe, this if else section can be done as a dictionary?, something like
```
const imagePaths = 
{
  currentTab.NEG: {
    1: "path"
    2: "path"
}
...
```

then you can do 
```
document.getElementById("graph-image").src = imagePaths[selectedTab][m]
```

this should look better

**Review by vjspranav — CHANGES_REQUESTED** [review]

**Comment by srisatyavinay** [comment]
As of now the images are not correct. We will change the image src soon.

File: experiment/simulation/js/flipflop.js (hunk 1 above)
Comment (srisatyavinay) [reply experiment/simulation/js/flipflop.js:29]: We want to leave them as for loop itself sir because changing everything will take a lot of time

File: experiment/simulation/js/flipflop.js (hunk 2 above)
Comment (srisatyavinay) [reply experiment/simulation/js/flipflop.js:42]: Now changed it into a javascript object

Comment (srisatyavinay) [reply experiment/simulation/js/flipflop.js]: Changed that into javascript objects
